// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using licenta.Data;

namespace licenta.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20210512102837_SeedQuestionsAnswers")]
    partial class SeedQuestionsAnswers
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.3")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CategoryQuestion", b =>
                {
                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<int>("QuestionId")
                        .HasColumnType("int");

                    b.HasKey("CategoryId", "QuestionId");

                    b.HasIndex("QuestionId");

                    b.ToTable("CategoryQuestion");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("licenta.Models.Answer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("bit");

                    b.Property<int>("QuestionId")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId");

                    b.ToTable("Answers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsCorrect = true,
                            QuestionId = 1,
                            Text = "panouri suplimentare la nodurile rutiere de pe autostrăzi;"
                        },
                        new
                        {
                            Id = 2,
                            IsCorrect = false,
                            QuestionId = 1,
                            Text = "panouri suplimentare pentru intersecţia cu calea ferată;"
                        },
                        new
                        {
                            Id = 3,
                            IsCorrect = false,
                            QuestionId = 1,
                            Text = "panouri succesive la apropierea de drumurile europene;"
                        },
                        new
                        {
                            Id = 4,
                            IsCorrect = false,
                            QuestionId = 2,
                            Text = "da, dacă accidentul nu s-a produs din vina dvs.;"
                        },
                        new
                        {
                            Id = 5,
                            IsCorrect = false,
                            QuestionId = 2,
                            Text = "da, în cazul în care motocicleta dvs. nu a fost avariată;"
                        },
                        new
                        {
                            Id = 6,
                            IsCorrect = true,
                            QuestionId = 2,
                            Text = "nu, întrucât săvârşiţi o infracţiune;"
                        },
                        new
                        {
                            Id = 7,
                            IsCorrect = false,
                            QuestionId = 3,
                            Text = "semnalizaţi înscrierea în curbă prin mijloace specifice;	"
                        },
                        new
                        {
                            Id = 8,
                            IsCorrect = true,
                            QuestionId = 3,
                            Text = "reduceţi viteza şi circulaţi cu atenţie, deoarece intraţi într-o curbă deosebit de periculoasă;	"
                        },
                        new
                        {
                            Id = 9,
                            IsCorrect = false,
                            QuestionId = 3,
                            Text = "semnalizaţi sonor intrarea în curbă;"
                        },
                        new
                        {
                            Id = 10,
                            IsCorrect = true,
                            QuestionId = 4,
                            Text = "dezinfectarea rănilor;	"
                        },
                        new
                        {
                            Id = 11,
                            IsCorrect = false,
                            QuestionId = 4,
                            Text = "calmarea durerilor;"
                        },
                        new
                        {
                            Id = 12,
                            IsCorrect = false,
                            QuestionId = 4,
                            Text = "oprirea hemoragiei."
                        },
                        new
                        {
                            Id = 13,
                            IsCorrect = false,
                            QuestionId = 5,
                            Text = "permite intrarea în intersecţie, dacă urmează după lumina verde;"
                        },
                        new
                        {
                            Id = 14,
                            IsCorrect = false,
                            QuestionId = 5,
                            Text = "permite schimbarea direcţiei de mers către dreapta;"
                        },
                        new
                        {
                            Id = 15,
                            IsCorrect = true,
                            QuestionId = 5,
                            Text = "interzice intrarea în intersecţie, dacă motocicleta poate fi oprită în condiţii de siguranţă;"
                        },
                        new
                        {
                            Id = 16,
                            IsCorrect = false,
                            QuestionId = 6,
                            Text = "să reducă viteza, întrucât se creează pericolul de blocare;"
                        },
                        new
                        {
                            Id = 17,
                            IsCorrect = true,
                            QuestionId = 6,
                            Text = "să oprească motocicleta, în afara situaţiilor impuse de trafic;"
                        },
                        new
                        {
                            Id = 18,
                            IsCorrect = false,
                            QuestionId = 6,
                            Text = "să întoarcă, prin ocolirea sensului giratoriu;	"
                        },
                        new
                        {
                            Id = 19,
                            IsCorrect = true,
                            QuestionId = 7,
                            Text = "reduceţi viteza şi opriţi înaintea semibarierelor;	"
                        },
                        new
                        {
                            Id = 20,
                            IsCorrect = false,
                            QuestionId = 7,
                            Text = "ocoliţi semibariera şi vă continuaţi drumul, dacă trenul nu se apropie;"
                        },
                        new
                        {
                            Id = 21,
                            IsCorrect = false,
                            QuestionId = 7,
                            Text = "măriţi viteza pentru a nu fi surprinşi de închiderea semibarierei;	"
                        },
                        new
                        {
                            Id = 22,
                            IsCorrect = false,
                            QuestionId = 8,
                            Text = "cel mult 10 zile de la data constatării evenimentului;	"
                        },
                        new
                        {
                            Id = 24,
                            IsCorrect = false,
                            QuestionId = 8,
                            Text = "până la expirarea asigurării obligatorii de răspundere civilă auto;"
                        },
                        new
                        {
                            Id = 25,
                            IsCorrect = true,
                            QuestionId = 8,
                            Text = "cel mult 30 zile de la data producerii avariei;"
                        },
                        new
                        {
                            Id = 26,
                            IsCorrect = false,
                            QuestionId = 9,
                            Text = "de la cel puţin 100 m;	"
                        },
                        new
                        {
                            Id = 27,
                            IsCorrect = false,
                            QuestionId = 9,
                            Text = "de la cel puţin 150 m;	"
                        },
                        new
                        {
                            Id = 28,
                            IsCorrect = true,
                            QuestionId = 9,
                            Text = "de la cel puţin 200 m;	"
                        },
                        new
                        {
                            Id = 29,
                            IsCorrect = false,
                            QuestionId = 11,
                            Text = "100 km/h;"
                        },
                        new
                        {
                            Id = 30,
                            IsCorrect = true,
                            QuestionId = 11,
                            Text = "130 km/h;"
                        },
                        new
                        {
                            Id = 31,
                            IsCorrect = false,
                            QuestionId = 11,
                            Text = "90 km/h;"
                        },
                        new
                        {
                            Id = 32,
                            IsCorrect = false,
                            QuestionId = 10,
                            Text = "acceleraţi şi treceţi cât mai repede peste calea ferată;"
                        },
                        new
                        {
                            Id = 33,
                            IsCorrect = true,
                            QuestionId = 10,
                            Text = "opriţi în faţa semibarierei;"
                        },
                        new
                        {
                            Id = 34,
                            IsCorrect = false,
                            QuestionId = 10,
                            Text = "dacă nu se apropie trenul, ocoliţi semibariera;"
                        },
                        new
                        {
                            Id = 35,
                            IsCorrect = false,
                            QuestionId = 12,
                            Text = "autoturismul, autocamionul, motocicleta;"
                        },
                        new
                        {
                            Id = 36,
                            IsCorrect = true,
                            QuestionId = 12,
                            Text = " autoturismul, motocicleta, autocamionul;"
                        },
                        new
                        {
                            Id = 37,
                            IsCorrect = false,
                            QuestionId = 12,
                            Text = "motocicleta, autoturismul, autocamionul."
                        },
                        new
                        {
                            Id = 38,
                            IsCorrect = true,
                            QuestionId = 13,
                            Text = "să permită controlul stării tehnice a motocicletei, precum şi al bunurilor transportate, în condiţiile legii"
                        },
                        new
                        {
                            Id = 40,
                            IsCorrect = true,
                            QuestionId = 13,
                            Text = "să se prezinte la verificarea medicală periodică, potrivit legii	"
                        },
                        new
                        {
                            Id = 42,
                            IsCorrect = false,
                            QuestionId = 13,
                            Text = "să transporte poliţişti, la cererea acestora;"
                        },
                        new
                        {
                            Id = 43,
                            IsCorrect = false,
                            QuestionId = 14,
                            Text = " atunci când traficul este redus;"
                        },
                        new
                        {
                            Id = 44,
                            IsCorrect = true,
                            QuestionId = 14,
                            Text = "atunci când semafoarele nu funcţionează ;"
                        },
                        new
                        {
                            Id = 45,
                            IsCorrect = false,
                            QuestionId = 14,
                            Text = "atunci când indicatoarele sunt instalate împreună cu semaforul pe acelaşi suport;"
                        },
                        new
                        {
                            Id = 46,
                            IsCorrect = false,
                            QuestionId = 15,
                            Text = "nu aveţi nicio obligaţie, deoarece semnalizarea nu vi se adresează;"
                        },
                        new
                        {
                            Id = 47,
                            IsCorrect = false,
                            QuestionId = 15,
                            Text = "opriţi până când acesta îşi începe din nou deplasarea;	"
                        },
                        new
                        {
                            Id = 48,
                            IsCorrect = true,
                            QuestionId = 15,
                            Text = "circulaţi cu atenţie sporită;"
                        },
                        new
                        {
                            Id = 49,
                            IsCorrect = true,
                            QuestionId = 16,
                            Text = "să ameninţe participanţii la trafic cu violenţe;"
                        },
                        new
                        {
                            Id = 50,
                            IsCorrect = true,
                            QuestionId = 16,
                            Text = "să săvârşească acte sau gesturi obscene;"
                        },
                        new
                        {
                            Id = 51,
                            IsCorrect = true,
                            QuestionId = 16,
                            Text = "să adreseze celorlalţi participanţi la trafic expresii jignitoare sau vulgare.	"
                        },
                        new
                        {
                            Id = 52,
                            IsCorrect = false,
                            QuestionId = 17,
                            Text = "indicatorul 1;"
                        },
                        new
                        {
                            Id = 53,
                            IsCorrect = true,
                            QuestionId = 17,
                            Text = "indicatorul 2;"
                        },
                        new
                        {
                            Id = 54,
                            IsCorrect = false,
                            QuestionId = 17,
                            Text = "niciunul."
                        },
                        new
                        {
                            Id = 55,
                            IsCorrect = false,
                            QuestionId = 18,
                            Text = "poliţiştii comunitari;	"
                        },
                        new
                        {
                            Id = 56,
                            IsCorrect = false,
                            QuestionId = 18,
                            Text = "personalul autorizat din cadrul serviciului examinări;	"
                        },
                        new
                        {
                            Id = 57,
                            IsCorrect = true,
                            QuestionId = 18,
                            Text = "personalul autorizat din zona lucrărilor pe drumurile publice.	"
                        },
                        new
                        {
                            Id = 58,
                            IsCorrect = false,
                            QuestionId = 19,
                            Text = "50 km/h;"
                        },
                        new
                        {
                            Id = 59,
                            IsCorrect = true,
                            QuestionId = 19,
                            Text = "80 km/h;"
                        },
                        new
                        {
                            Id = 60,
                            IsCorrect = false,
                            QuestionId = 19,
                            Text = "100 km/h;"
                        },
                        new
                        {
                            Id = 61,
                            IsCorrect = false,
                            QuestionId = 20,
                            Text = "70 km/h;"
                        },
                        new
                        {
                            Id = 62,
                            IsCorrect = false,
                            QuestionId = 20,
                            Text = "90 km/h;"
                        },
                        new
                        {
                            Id = 63,
                            IsCorrect = true,
                            QuestionId = 20,
                            Text = "100 km/h."
                        },
                        new
                        {
                            Id = 64,
                            IsCorrect = false,
                            QuestionId = 21,
                            Text = "pentru lipsa triunghiurilor reflectorizante;"
                        },
                        new
                        {
                            Id = 65,
                            IsCorrect = false,
                            QuestionId = 21,
                            Text = "pentru lipsa trusei medicale de prim ajutor;"
                        },
                        new
                        {
                            Id = 66,
                            IsCorrect = true,
                            QuestionId = 21,
                            Text = "pentru refuzul de legitimare;"
                        },
                        new
                        {
                            Id = 67,
                            IsCorrect = false,
                            QuestionId = 22,
                            Text = "folosirea mijloacelor de avertizare sonoră;"
                        },
                        new
                        {
                            Id = 68,
                            IsCorrect = false,
                            QuestionId = 22,
                            Text = "remorcarea altui autovehicul;"
                        },
                        new
                        {
                            Id = 69,
                            IsCorrect = true,
                            QuestionId = 22,
                            Text = "staţionarea voluntară pe partea carosabilă;"
                        },
                        new
                        {
                            Id = 70,
                            IsCorrect = true,
                            QuestionId = 23,
                            Text = "să verificaţi o dată pe lună, la rece, presiunea din pneuri;"
                        },
                        new
                        {
                            Id = 71,
                            IsCorrect = true,
                            QuestionId = 23,
                            Text = "să schimbaţi între ele pneurile, la aproximativ 10 000 km;	"
                        },
                        new
                        {
                            Id = 72,
                            IsCorrect = true,
                            QuestionId = 23,
                            Text = "să înlocuiţi pneurile la fiecare 1000 km."
                        },
                        new
                        {
                            Id = 73,
                            IsCorrect = false,
                            QuestionId = 24,
                            Text = "semnalul luminos al semaforului instalat pe trotuar;"
                        },
                        new
                        {
                            Id = 74,
                            IsCorrect = true,
                            QuestionId = 24,
                            Text = "semnalul luminos al semaforului instalat pe consolă;"
                        },
                        new
                        {
                            Id = 75,
                            IsCorrect = false,
                            QuestionId = 24,
                            Text = "semnalul luminos al oricăruia dintre semafoare;"
                        },
                        new
                        {
                            Id = 76,
                            IsCorrect = true,
                            QuestionId = 25,
                            Text = "mărirea vitezei de deplasare sau grăbirea traversării drumului de către pietoni;	"
                        },
                        new
                        {
                            Id = 77,
                            IsCorrect = false,
                            QuestionId = 25,
                            Text = "oprirea temporară a circulaţiei;"
                        },
                        new
                        {
                            Id = 78,
                            IsCorrect = false,
                            QuestionId = 25,
                            Text = "reducerea vitezei de deplasare;"
                        },
                        new
                        {
                            Id = 79,
                            IsCorrect = true,
                            QuestionId = 26,
                            Text = "reduceţi viteza şi opriţi înaintea semibarierelor;	"
                        },
                        new
                        {
                            Id = 80,
                            IsCorrect = false,
                            QuestionId = 26,
                            Text = "ocoliţi semibariera şi vă continuaţi drumul, dacă trenul nu se apropie;"
                        },
                        new
                        {
                            Id = 81,
                            IsCorrect = false,
                            QuestionId = 26,
                            Text = "măriţi viteza pentru a nu fi surprinşi de închiderea semibarierei;	"
                        },
                        new
                        {
                            Id = 82,
                            IsCorrect = false,
                            QuestionId = 27,
                            Text = "cel mult 10 zile de la data constatării evenimentului;	"
                        },
                        new
                        {
                            Id = 83,
                            IsCorrect = false,
                            QuestionId = 27,
                            Text = "până la expirarea asigurării obligatorii de răspundere civilă auto;"
                        },
                        new
                        {
                            Id = 84,
                            IsCorrect = true,
                            QuestionId = 27,
                            Text = "cel mult 30 zile de la data producerii avariei;"
                        });
                });

            modelBuilder.Entity("licenta.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<DateTime>("Birthday")
                        .HasColumnType("datetime2");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers");
                });

            modelBuilder.Entity("licenta.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("NumberOfQuestions")
                        .HasColumnType("int");

                    b.Property<int>("NumberOfWrongQuestions")
                        .HasColumnType("int");

                    b.Property<int>("Time")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "A, A1, A2, AM",
                            NumberOfQuestions = 20,
                            NumberOfWrongQuestions = 4,
                            Time = 20
                        });
                });

            modelBuilder.Entity("licenta.Models.Connection", b =>
                {
                    b.Property<string>("ConnectionID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ApplicationUserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("IsConnected")
                        .HasColumnType("bit");

                    b.Property<string>("UserAgent")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ConnectionID");

                    b.HasIndex("ApplicationUserId");

                    b.ToTable("Connections");
                });

            modelBuilder.Entity("licenta.Models.Message", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ApplicationUserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsSeen")
                        .HasColumnType("bit");

                    b.Property<string>("ReceiverUsername")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("SenderUsername")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationUserId");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("licenta.Models.Note", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("EndHour")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("StartHour")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Notes");
                });

            modelBuilder.Entity("licenta.Models.Question", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Explanation")
                        .IsRequired()
                        .HasMaxLength(1200)
                        .HasColumnType("nvarchar(1200)");

                    b.Property<string>("ImagePath")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsDisputed")
                        .HasColumnType("bit");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.ToTable("Question");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Explanation = "Panourile din imagine se numesc ,,Panouri suplimentare la nodurile rutiere de pe autostrăzi”. Aceste panouri se găsesc instalate după cum urmează: primul, cel cu trei linii, la 300 de metri; al doilea, cel cu doua linii la 200 de metri si al treilea; cel cu o linie la 100 de metri de o iesire de pe autostrada.",
                            ImagePath = "/Images/QuestionImage/1.png",
                            IsDisputed = false,
                            Text = "Ce semnificaţie au panourile alăturate?"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Explanation = "Dacă ați fost implicat într-un accident de circulație în urmă căruia a rezultat moartea sau vătămarea integrității corporale ori a sănătații unei persoane sunteți obligat să anunțați imediat poliția la numărul naţional unic pentru apeluri de urgenţă 112, să nu modificați sau să ștergeti urmele accidentului și să nu parasiți locul faptei. Dacă ați fost implicat într-un accident de circulație în urmă căruia a rezultat moartea sau vătămarea integrității corporale ori a sănătații unei persoane sunteți obligat să anunțați imediat poliția la numărul naţional unic pentru apeluri de urgenţă 112, să nu modificați sau să ștergeti urmele accidentului și să nu parasiți locul faptei.",
                            IsDisputed = false,
                            Text = "În cazul implicării într-un accident, puteţi părăsi locul acestuia fără încuviinţarea poliţiei, dacă a rezultat vătămarea integrităţii corporale a unei persoane?"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            Explanation = "Indicatorul pe care l-ați întâlnit se numește “Curbă deosebit de periculoasă”. Acest indicator ne avertizează că urmează o curbă deosebit de periculoasă către dreapta. La întâlnirea lui se impune reducerea vitezei de deplasare la 30 de km/h în localități și 50 de km/h în afara localităților, toate manevrele (depășirea, oprirea, staționarea, mersul înapoi și întoarcerea) fiind interzise.",
                            ImagePath = "/Images/QuestionImage/2.png",
                            IsDisputed = false,
                            Text = "Ce trebuie să faceţi când întâlniţi indicatorul din imagine?"
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 1,
                            Explanation = "Substanțele antiseptice sunt substanțe dezinfectante care previn ori înlăturarea infecțiile microbiene. Acestea se folosesc în dezinfectarea rănilor.",
                            IsDisputed = false,
                            Text = "Substanţele antiseptice se folosesc pentru:	"
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 1,
                            Explanation = "Cand semnalul de culoare galbena apare dupa semnalul de culoare verde, conducatorul vehiculului care se apropie de intersectie nu trebuie sa treaca de locurile prevazute la art. 52 alin. (2), cu exceptia situatiei in care, la aparitia semnalului, se afla atat de aproape de acele locuri incat nu ar mai putea opri vehiculul in conditii de siguranta.",
                            IsDisputed = false,
                            Text = "Semnalul galben al semaforului:"
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 1,
                            Explanation = "some",
                            IsDisputed = false,
                            Text = "Într-o intersecţie unde circulaţia se desfăşoară în sens giratoriu, conducătorului unei motociclete îi este interzis:"
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 1,
                            Explanation = "La apropierea de o trecere la nivel cu o cale ferată prevăzută cu semibariere automate, semnalele sonore și luminile roșii fiind în funcțiune, aveți obligația de a reduce viteza și de a opri autovehiculul înaintea semibarierelor.	",
                            IsDisputed = false,
                            Text = "Cum veţi proceda corect dacă, la apropierea de o trecere la nivel cu o cale ferată prevăzută cu semibariere automate, luminile roşii şi semnalele sonore sunt în funcţiune?	"
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 1,
                            Explanation = "Conducătorului auto îi este interzis să circule cu autovehiculul avariat mai mult de 30 de zile de la producerea avarierei.	",
                            IsDisputed = false,
                            Text = "Aveţi posibilitatea de a circula pe drumurile publice cu motocicleta avariată:"
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 1,
                            Explanation = "Pe timpul nopții, la apropierea de un alt vehicul care circulă din sens opus, sunteți obligat ca de la distanța de cel puțin 200 de metri să folosiți luminile de întâlnire concomitent cu reducerea vitezei.",
                            IsDisputed = false,
                            Text = "De la ce distanţă faţă de vehiculul care circulă din sens opus, pe timp de noapte, conducătorul unei motociclete este obligat să folosească lumina de întâlnire?"
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 1,
                            Explanation = "Pe timpul nopții la apropierea de un alt vehicul care circulă din sens opus, sunteți obligat ca de la distanța de cel putin 200 de metri să folosiți luminile de întalnire concomitent cu reducerea vitezei.",
                            IsDisputed = false,
                            Text = "Vă apropiaţi de o trecere peste calea ferată şi observaţi că se coboară semibariera. Cum procedaţi?	"
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 1,
                            Explanation = "Vitezele maxime în afara localităților pentru categoriile și subgategoriile de autovehicule prevăzute la  art. 15 alin. (2) sunt următoarele: 130km/h pe autostrăzi, 100km/h pe drumurile expres sau pe cele naționle europene (E) și 90 km/h pe celelalte categorii de drummuri, pentru autovehiculele din categoriile A și B.",
                            IsDisputed = false,
                            Text = "Care este limita maximă de viteză cu care aveţi voie să conduceţi un autovehicul aparţinând categoriei A, pe autostrăzi?"
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 1,
                            Explanation = "Intesecția din imagine este dirijată prin indicatoare de reglementare de prioritate. Autocamionul vine de pe drumul fără prioritate și trebuie să îi acorde prioritate de trecere motocicletei și autoturismului. Între autoturism și motocicletă s-a crea o situație de egalitate, situație în cre se va aplica regula priorității de dreapta, deci în această situație motocicleta îi va acorda prioritate autoturismului deoarece virând către stânga autoturismul îi va veni din partea dreaptă.",
                            ImagePath = "/Images/QuestionImage/3.png",
                            IsDisputed = false,
                            Text = "Care este ordinea de intrare în intersecţie?"
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 1,
                            Explanation = "Conducătorul de autovehicul este obligat să permită controlul stării tehnice a vehiculului, precum și al bunurilor transportate. Această verificare a stării tehnice avehiculelor aflate în trafic pe drumurile publice se face de către poliția rutieră, împreună cu instituțiile abilitate de lege și să se prezinte la verificarea medicală periodică, potrivit legii.",
                            IsDisputed = false,
                            Text = "Conducătorul unei motociclete este obligat:	"
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 1,
                            Explanation = "Într-o intersecție dirijată cu semanle luminoase în care unt instalate și indicatoare de reglare de prioritate, conducătorul de vehicul este obligat să respecte semnalele luminoase cu prioritate de față de indicatoarele de reglare de prioritate.",
                            IsDisputed = false,
                            Text = "Semnificaţia indicatoarelor „Oprire” şi „Cedează trecerea”, instalate în intersecţiile semaforizate, trebuie respectată"
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 1,
                            Explanation = "Legislația din România nu obligă la oprire în această situație. Dacă șoferul autobuzului școlar pune în funcțiune luminile deavarie, o face pentru a avertiza cillți particpanți la trafic că acesta constituie un pericol pentru ceilalți participanți la trafic, iar din punct de vdere al conduitei preventive se recomandă reducerea vitezei și sporirea atenției.",
                            IsDisputed = false,
                            Text = "Cum trebuie să procedaţi atunci când un autobuz şcolar opreşte, cu luminile intermitente de avertizare aprinse?	"
                        },
                        new
                        {
                            Id = 16,
                            CategoryId = 1,
                            Explanation = "Este interzis conducătorilor de autovehicule să amenințe participanții la trafic cu violențe, să săvârșească acte sau gesturi obscene sau să adreseze celorlalți particpanți la trafic expresii jignitoare sau vulgare.",
                            IsDisputed = false,
                            Text = "Conducătorilor de motociclete le este interzis:	"
                        },
                        new
                        {
                            Id = 17,
                            CategoryId = 1,
                            Explanation = "Indicaorul 1 se numește ,,Înainte”, aces indicator obligăconducătorii devehicule să crcule pe direcție înainte în prime întersecție. Indicatorul 2 se  numește ,,Sens unic”, acest indicator are rolul dea informa conducătorii de vehicule că drumul pe care circulă este un drum cu sens unic.",
                            ImagePath = "/Images/QuestionImage/4.png",
                            IsDisputed = false,
                            Text = "Ce indicator arată că circulaţia se desfăşoară într-un singur sens?"
                        },
                        new
                        {
                            Id = 18,
                            CategoryId = 1,
                            Explanation = "Participanții la trafic sunt obligați să oprească la semnalele adresate de poliţiştii de frontieră circulație, îndrumătorii de circulaţie ai Ministerului Apărării, agenţii de cale ferată, la trecerile la nivel, personalul autorizat din zona lucrărilor pe drumurile publice, membrii patrulelor şcolare de circulaţie, la trecerile pentru pietoni din apropierea unităţilor de învățământ, precum și ale nevăzătorilor, prin ridicarea bastonului alb atunci când aceştia traversează strada. NU aveți obligația să opriți la semnalele adresate de poliţiştii comunitari și personalul autorizat din cadrul serviciului examinări.",
                            IsDisputed = false,
                            Text = "Aveţi obligaţia de a opri imediat motocicleta la semnalele adresate de:"
                        },
                        new
                        {
                            Id = 19,
                            CategoryId = 1,
                            Explanation = "Pe drumurile naționale europene din afara localităților,  limita maximă de viteză pentru un autovehicul aparținând subcategoriei A1 este de 80km/h.",
                            IsDisputed = false,
                            Text = "Care este limita maximă de viteză cu care aveţi voie să conduceţi, pe drumurile naţionale europene din localităţi, un autovehicul aparţinând subcategoriei A1?"
                        },
                        new
                        {
                            Id = 20,
                            CategoryId = 1,
                            Explanation = "Pe drumurile naționale europene din afara localităților, limita maximă de viteză cu care aveți voie să conduceți un autovehicul aparținând categoriei A este de 100km/h.",
                            IsDisputed = false,
                            Text = "Care este limita maximă de viteză cu care aveţi voie să conduceţi, pe drumurile naţionale europene din afara localităţilor, un autovehicul aparţinând categoriei A?	"
                        },
                        new
                        {
                            Id = 21,
                            CategoryId = 1,
                            Explanation = "Imobilizarea unui vehicul de către polițistul rutier se dispune pentru refuzul conducătorului de a se legitima. Nu se imobilizează vehiculul pentru lipsa triunghiurilor reflectorizante sau pentru lipsa trusei medicale de prim ajutor.",
                            IsDisputed = false,
                            Text = "Imobilizarea unei motociclete de către poliţistul rutier se dispune:"
                        },
                        new
                        {
                            Id = 22,
                            CategoryId = 1,
                            Explanation = "Se interzice staționarea vehiculelor în toate cazurile în care este interzisă oprirea voluntară a vehiculelor, iar oprirea voluntară vă este interzisă pe partea carosabilă a drumurilor național europene (E) și bineînțeles vă este interzisă și staționarea.	",
                            IsDisputed = false,
                            Text = "Când circulaţi pe un drum naţional european vă este interzisă:"
                        },
                        new
                        {
                            Id = 23,
                            CategoryId = 1,
                            Explanation = "Pentru a conduce ecologic un autovehiculul trebuie să luați toate măsurile necesare pentru a reduce consumul de combustibil. Prin urmare, pentru a avea un consum optim de carburant, este necesar să verificaţi presiunea pneurilor o dată pe lună, la rece, altfel spus atunci când vehiculul nu a circulat mai mult de 2 ore. Pentru a vă asigura că presiunea aerului este adecvată, nu vă raportaţi la indicaţiile scrise chiar pe pneu, pentru că acestea arata presiunea maximă. Este preferabil să consultaţi manualul producatorului maşinii dumneavoastră. Pentru a conduce ecologic un autovehiculul trebuie să luați toate măsurile necesare pentru a reduce poluarea mediului înconjurător. Prin urmare, pentru a reducere poluarea mediului, este necesar să schimbaţi între ele pneurile (permutaţi) la fiecare 10.000 de km şi efectuaţi reglajul geometriei şi echilibrarea roţilor o dată pe an, lucru care duce la uzarea uniformă a pneurilor. Această masură va crește durata de viață a anvelopelor și astfel se va reduce poluarea.",
                            IsDisputed = false,
                            Text = "Pentru a conduce ecologic un autovehiculul, este necesar:"
                        },
                        new
                        {
                            Id = 24,
                            CategoryId = 1,
                            Explanation = "Motociclistul din imagine vrea să schimbe direcţia de mers către stânga, acesta s-a încadrat corect pe banda de viraj la stânga și trebuie să respecte semnalul luminos al semaforului instalat pe consolă.",
                            ImagePath = "/Images/QuestionImage/6.png",
                            IsDisputed = false,
                            Text = "Motociclistul care vrea să schimbe direcţia de mers trebuie să respecte:"
                        },
                        new
                        {
                            Id = 25,
                            CategoryId = 1,
                            Explanation = "Semnalul adresat de către polițistul rutier prin rotirea vioaie a brațului, semnifică mărirea vitezei de deplasare a vehiculelor sau grăbirea traversării drumului de către pietoni.	",
                            IsDisputed = false,
                            Text = "Rotirea vioaie a braţului poliţistului semnifică:"
                        },
                        new
                        {
                            Id = 26,
                            CategoryId = 1,
                            Explanation = "La apropierea de o trecere la nivel cu o cale ferată prevazută cu semibariere automate, semnalele sonore și luminile roșii fiind în funcțiune, aveți obligația de a reduce viteza și de a opri autovehiculul înaintea semibarierelor.	",
                            IsDisputed = false,
                            Text = "Cum veţi proceda corect dacă, la apropierea de o trecere la nivel cu o cale ferată prevăzută cu semibariere automate, luminile roşii şi semnalele sonore sunt în funcţiune?	"
                        },
                        new
                        {
                            Id = 27,
                            CategoryId = 1,
                            Explanation = "Conducătorului de autovehicul îi este interzis să circule cu autovehiculul avariat mai mult de 30 de zile de la producerea avariei.",
                            IsDisputed = false,
                            Text = "Aveţi posibilitatea de a circula pe drumurile publice cu motocicleta avariată:	"
                        });
                });

            modelBuilder.Entity("licenta.Models.Test", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ApplicationUserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("NumberOfCorrectAnswers")
                        .HasColumnType("int");

                    b.Property<bool>("Passed")
                        .HasColumnType("bit");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationUserId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Tests");
                });

            modelBuilder.Entity("CategoryQuestion", b =>
                {
                    b.HasOne("licenta.Models.Category", null)
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("licenta.Models.Question", null)
                        .WithMany()
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("licenta.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("licenta.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("licenta.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("licenta.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("licenta.Models.Answer", b =>
                {
                    b.HasOne("licenta.Models.Question", "Questions")
                        .WithMany("Answers")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Questions");
                });

            modelBuilder.Entity("licenta.Models.Connection", b =>
                {
                    b.HasOne("licenta.Models.ApplicationUser", null)
                        .WithMany("Connections")
                        .HasForeignKey("ApplicationUserId");
                });

            modelBuilder.Entity("licenta.Models.Message", b =>
                {
                    b.HasOne("licenta.Models.ApplicationUser", null)
                        .WithMany("Messages")
                        .HasForeignKey("ApplicationUserId");
                });

            modelBuilder.Entity("licenta.Models.Test", b =>
                {
                    b.HasOne("licenta.Models.ApplicationUser", null)
                        .WithMany("Tests")
                        .HasForeignKey("ApplicationUserId");

                    b.HasOne("licenta.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("licenta.Models.ApplicationUser", b =>
                {
                    b.Navigation("Connections");

                    b.Navigation("Messages");

                    b.Navigation("Tests");
                });

            modelBuilder.Entity("licenta.Models.Question", b =>
                {
                    b.Navigation("Answers");
                });
#pragma warning restore 612, 618
        }
    }
}
